spring:
  config:
     import: optional:configserver:http://localhost:8888
  application:
    name: ApplicationRegistrationService
  boot:
    admin:
      client:
        url: http://localhost:9999
management:
  endpoint:
    env:
      enabled: true
      show-values: always
    health:
      show-details: always
  endpoints:
    web:
      exposure:
         include: '*'
        
  
eureka:
  client:
     service-url:
        default-zone: http://localhost:8761/eureka
server:
  port: 4041   
arm:
  ssa-web:
    url: http://localhost:9090/ssa-web-api/find/{ssn}   
  stateName: california   
