spring:
  config:
    import: "optional:configserver:"
  application:
    name: CorrespondenceService
  boot:
    admin:
      client:
        url: http://localhost:9999

  mail:
     host: smtp.gmail.com
     port: 587
     username: kanakarajujami409@gmail.com
     password: qtfugntfjxuyfgkk
     properties:
         mail:
           transport:
              protocol: smtp
           smtp:
              port: 587
              auth: true
              starttls:
                  enable: true
                  required: true 
management:
  endpoint:
    env:
      enabled: true
      show-values: always  
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*" 
server:
   port: 4045
eureka:   
   client:
      service-url:
            default-zone: http://localhost:8761/eureka