spring:
  config:
     import: "optional:configserver:"
  application:
    name: EligibilityDeterminationService
  boot:
    admin:
      client:
        url: http://localhost:9999
management:
  endpoint:
    env:
     enabled: true
     show-values: always  
    health:
     show-details: always
  endpoints:
    web:
      exposure:
        include: "*" 

server:
  port: 4043  
