spring:
  application:
    name: EligibilityDeterminationService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ish_database
    username: root
    password: Kanakaraju@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 4043  
